version: '3'

volumes:
  postgres_test_volume:

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_test_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=patients
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  health-crud:
    build:
      dockerfile: Dockerfile.dev
      context: .
    working_dir: /usr/src/app/
    volumes:
      - .:/usr/src/app/
    command: "lein run"
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/patients
    depends_on:
      - db