name: Clojure CI

on:
  push:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@latest
    - uses: DeLaGuardo/setup-graalvm@2.0
      with:
        graalvm-version: '19.3.1.java11'
    - uses: DeLaGuardo/setup-clojure@2.0
      with:
        tools-deps: '1.10.1.469'
    - name: Install dependencies
      run: clj -Sdeps
      
    - name: Run checks
      run: make checks
      
    - name: Run tests
      run: make tests
  #cd:
  #  runs-on: ubuntu-latest
  #  needs: ci
  #  
  #  steps:
  #  - uses: actions/checkout@v2
  #  - name: Docker login
  #    run: docker login --username ${{ secrets.DOCKER_LOGIN }} --password ${{ secrets.DOCKER_TOKEN }}
  #  - name: Build
  #    run: docker build -t health-crud .
  #  - name: Tags
  #    run: |
  #      docker tag health-crud ${{ secrets.DOCKER_LOGIN }}/health-crud:${{ github.sha }}
  #      docker tag health-crud ${{ secrets.DOCKER_LOGIN }}/health-crud:latest
  #  - name: Push
  #    run: |
  #      docker push ${{ secrets.DOCKER_LOGIN }}/health-crud:${{ github.sha }}
  #      docker push ${{ secrets.DOCKER_LOGIN }}/health-crud:latest
